# Schema for the configuration files of the mail task module.
mail_task.settings:
  type: config_object
  label: 'mail task settings'
  mapping:
    example:
      type: string
      label: 'Example'
