# Schema for the configuration files of the render block module.
render_block.settings:
  type: config_object
  label: 'render block settings'
  mapping:
    example:
      type: string
      label: 'Example'
